<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityAgent.Core\SecurityAgent.Core.csproj" />
    <ProjectReference Include="..\SecurityAgent.StatusContract\SecurityAgent.StatusContract.csproj" />
  </ItemGroup>

</Project>
